version: '3.4'

services:
  db:
    ports:
      - "5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment: 
      DB_CONNECTION_STRING: "host=db;port=5432;database=posts;username=postgres;password=example"
    depends_on: 
      - "db"
  web:
    image: nginx:latest
    volumes:
      - ./web/static:/usr/share/nginx/html/
    ports:
      - "80:80"