version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  web:
    image: nginx:latest
    volumes:
      - ./web/static:/usr/share/nginx/html/
    ports:
      - "80:80"